Setup Check Style
CottaCush/AndroidBaseProject pull request #13
Opened 2018-06-07 13:05 UTC by JohnItoo

2018-06-07 13:10 UTC, JubrilEdu requested changes

2018-06-07 13:10 UTC, djubreel commented on app/src/main/java/com/cottacush/android/baseProject/BaseActivity.java
> +                                               positiveClickListener, String negativeText,
Can you have a look at the formatting of this file?

2018-06-07 13:56 UTC, helios66 requested changes

2018-06-07 13:56 UTC, helios66 commented on config/quality.gradle
> +    checkstyle 'com.puppycrawl.tools:checkstyle:6.11.1'
Can information about this checkstyle component be added to the README.md file?

2018-07-30 10:05 UTC, JubrilEdu approved these changes

2018-08-06 09:11 UTC, oyeleke approved these changes

2018-08-06 09:19 UTC, merged