Setup Check Style, OAuth config
CottaCush/AndroidBaseProject pull request #8
Opened 2018-01-06 09:53 UTC by codedentwickler

feat: Add convenience Wrapper around Retrofit callback to handle common network errors
feat: Setup Checkstyle on Base project
feat: Add Gradle task for Checkstyle
fix: Gradle deprecation issues on android studio 3.0

2018-01-06 14:10 UTC, rasheedsulayman approved these changes

2018-01-30 05:12 UTC, goke-epapa requested changes
This is good work, well done. After merging @djubreel PR, there are conflicts you need to resolve @codedentwickler .

2018-01-30 05:12 UTC, goke-epapa commented on app/build.gradle
> +    return new Date().format("MMM dd yyyy", TimeZone.getTimeZone("UTC"))
Please don't add the date and time to the app filename, let's work with semantic versioning.

2018-08-06 09:17 UTC, JohnItoo commented
Most of the changes on this pull request were effected on a similar pull request : https://github.com/CottaCush/AndroidBaseProject/pull/13

2018-08-06 09:17 UTC, closed without merging